### ISSUE TITLE
Orebfuscator causing lag

### ISSUE THREAD

**Issue by jordanwilliams1** [lishid/Orebfuscator#143]
Hello, 

After a few hours of the server running we seem to get HUGE lag spikes. Massivelag is just spamming us with this plugin.
https://hastebin.com/oramiyuciv.md

Any ideas? It seems to run find for a few hours then just starts going nuts and spamming this in massivelag.

Server stops getting huge lag spikes when it drops below 60. When its around 70+ We seem to get huge lagspikes :(

**Comment by jordanwilliams1** [comment]
Lag spike stop after plugin is disabled. "/ofc disable" back to a 20tps smooth.

**Comment by ProgrammerDan** [comment]
Wow, this is a new one. Thanks for the hastebin -- can you also show us your Orebfuscator config, as well as what other plugins you are running that deal with chunk loading / unloading, and block manipulation?

**Comment by MrPowerGamerBR** [comment]
Same here, Orebfuscator engine mode 2 causes the "doChunkMap" timings go to a whopping 68%, engine mode 1 is a bit less laggy, but still lags a lot.

Disabling Orebfuscator fixes the problem entirely. (drops the doChunkMap timings to only 0.22%)

**Comment by RoboMWM** [comment]
Isolated, controlled tests as well as linking the respective timing reports would help.

**Comment by ProgrammerDan** [comment]
Yes please, I cannot diagnose in a vacuum. @MrPowerGamerBR As requested before:

show us your Orebfuscator config, as well as what other plugins you are running that deal with chunk loading / unloading, and block manipulation?

**Comment by MrPowerGamerBR** [comment]
@ProgrammerDan I was going to share my Timings, but I'm still trying to figure out if it is Orebfuscator or not.

But anyway, if you *really* want to check it, here it is: https://timings.aikar.co/?id=59f0b1aa021146d3b3249219e8677f78

Config:
```
ConfigVersion: 13
Booleans:
  UseCache: true
  Enabled: true
  UpdateOnDamage: true
  NoObfuscationForMetadata: true
  NoObfuscationForOps: false
  NoObfuscationForPermission: false
  LoginNotification: true
Integers:
  MaxLoadedCacheFiles: 256
  DeleteCacheFilesAfterDays: 0
  EngineMode: 2
  InitialRadius: 1
  UpdateRadius: 6
Strings:
  CacheLocation: orebfuscator_cache
  NoObfuscationForMetadataTagName: NPC
Lists:
  TransparentBlocks: []
  NonTransparentBlocks: []
Worlds:
  Default:
    Types:
    - DEFAULT
    Enabled: true
    AntiTexturePackAndFreecam: true
    AirGeneratorMaxChance: 43
    DarknessHideBlocks: false
    DarknessBlocks:
    - MOB_SPAWNER
    - CHEST
    Mode1Block: STONE
    RandomBlocks: []
    ObfuscateBlocks: []
    ProximityHider:
      Enabled: false
      Distance: 8
      SpecialBlock: STONE
      Y: 255
      UseSpecialBlock: false
      ObfuscateAboveY: false
      ProximityHiderBlocks:
      - DISPENSER
      - MOB_SPAWNER
      - CHEST
      - DIAMOND_ORE
      - WORKBENCH
      - FURNACE
      - BURNING_FURNACE
      - ENCHANTMENT_TABLE
      - EMERALD_ORE
      - ENDER_CHEST
      - ANVIL
      - TRAPPED_CHEST
  Normal:
    Types:
    - NORMAL
    Mode1Block: STONE
    RandomBlocks:
    - STONE
    - COBBLESTONE
    - WOOD
    - GOLD_ORE
    - IRON_ORE
    - COAL_ORE
    - LAPIS_ORE
    - TNT
    - MOSSY_COBBLESTONE
    - OBSIDIAN
    - DIAMOND_ORE
    - REDSTONE_ORE
    - CLAY
    - EMERALD_ORE
    ObfuscateBlocks:
    - GOLD_ORE
    - IRON_ORE
    - COAL_ORE
    - LAPIS_ORE
    - CHEST
    - DIAMOND_ORE
    - REDSTONE_ORE
    - GLOWING_REDSTONE_ORE
    - EMERALD_ORE
    - ENDER_CHEST
  TheEnd:
    Types:
    - THE_END
    Mode1Block: ENDER_STONE
    RandomBlocks:
    - BEDROCK
    - OBSIDIAN
    - ENDER_STONE
    - PURPUR_BLOCK
    - END_BRICKS
    ObfuscateBlocks:
    - ENDER_STONE
  Nether:
    Types:
    - NETHER
    Mode1Block: NETHERRACK
    RandomBlocks:
    - GRAVEL
    - NETHERRACK
    - SOUL_SAND
    - NETHER_BRICK
    - QUARTZ_ORE
    ObfuscateBlocks:
    - NETHERRACK
    - QUARTZ_ORE
```
