### ISSUE TITLE
Cannot Disable or Enable Worlds & /ofc <enable/disable> world Not Working

### ISSUE THREAD

**Issue by jessefjxm** [lishid/Orebfuscator#149]
Using spigot 1.10.2, newest OFC.
Goal: enable OFC in 'Mineral', disable it in other worlds (NewSurvival2017, ...). All mentioned worlds are normal worlds.
Following guide: https://github.com/lishid/Orebfuscator/wiki/Configuration-File#example-how-to-disable-or-enable-worlds

I've tried every combination I can think about that mentioned on wiki. It almost drives me mad.

Part 1. Command

All following commands return full command help and no positive or negtive response.
/ofc disable world Spawn
/ofc disable Spawn
/ofc enable world Mineral
/ofc enable Mineral

Part 2. Configuration

All following attempts cannot achieve my attempt.

Attempt 1: put DisabledWorlds before default settings (Default, Normal, Nether...)
Result 1: OFC still working on all worlds.
https://pastebin.com/svHMNahx
Attempt 2: disable default and add EnabledWorlds after default seetings.
Result 2: OFC disabled in all worlds.
https://pastebin.com/UbxKP7fv
Attempt 3: put DisabledWorlds before DEFAULT, remove others (Normal removed as well).
Result 3: OFC not working.
https://pastebin.com/SvpPQHQg
Attempt 4: disable default and add EnabledWorlds after it, remove others (Normal removed as well).
Result 4: OFC not working.
https://pastebin.com/4hNn00xj
Attempt 5: Inherited from Attemp 4. Add detail settings to EnabledWorlds.
Result 5: OFC not working.
https://pastebin.com/RZCyg8iC
Attempt 6: Inherited from Attemp 5. Add 'TYPE: NORMAL' to EnabledWorlds.
Result 6: OFC wokring on all normal worlds.
https://pastebin.com/HGiC9G6E

**Comment by ProgrammerDan** [comment]
Placeholder note: I'm working on this for you. Should have config soon.

**Comment by ProgrammerDan** [comment]
Confirmed this works as intended:

```
ConfigVersion: 13
Integers:
 EngineMode: 2
 MaxLoadedCacheFiles: 64
 DeleteCacheFilesAfterDays: 0
 InitialRadius: 1
 UpdateRadius: 2
Booleans: 
 Enabled: true
 UseCache: true
 UpdateOnDamage: true
 NoObfuscationForOps: false
 NoObfuscationForPermission: true
 NoObfuscationForMetadata: true
 LoginNotification: true
Lists:
 TransparentBlocks: []
 NonTransparentBlocks: []
Strings:
 CacheLocation: orebfuscator_cache
 NoObfuscationForMetadataTagName: NPC
Worlds:
  DefaultEverythingOff:
    Types:
    - DEFAULT
    Enabled: false
  SelectiveOn:
    Names:
    - Mineral
    Enabled: true
    AntiTexturePackAndFreecam: true
    AirGeneratorMaxChance: 43
    DarknessHideBlocks: false
    DarknessBlocks:
    - MOB_SPAWNER
    - CHEST
    Mode1Block: STONE
    RandomBlocks:
    - STONE
    - COBBLESTONE
    - WOOD
    - GOLD_ORE
    - IRON_ORE
    - COAL_ORE
    - LAPIS_ORE
    - TNT
    - MOSSY_COBBLESTONE
    - OBSIDIAN
    - DIAMOND_ORE
    - REDSTONE_ORE
    - CLAY
    - EMERALD_ORE
    ObfuscateBlocks:
    - GOLD_ORE
    - IRON_ORE
    - COAL_ORE
    - LAPIS_ORE
    - CHEST
    - DIAMOND_ORE
    - REDSTONE_ORE
    - GLOWING_REDSTONE_ORE
    - EMERALD_ORE
    - ENDER_CHEST
    ProximityHider:
      Enabled: true
      Distance: 5
      SpecialBlock: STONE
      Y: 255
      UseSpecialBlock: true
      ObfuscateAboveY: false
      ProximityHiderBlocks:
      - DISPENSER
      - MOB_SPAWNER
      - CHEST
      - DIAMOND_ORE
      - WORKBENCH
      - FURNACE
      - BURNING_FURNACE
      - ENCHANTMENT_TABLE
      - EMERALD_ORE
      - ENDER_CHEST
      - ANVIL
      - TRAPPED_CHEST
```

If you'd like more worlds enabled, just add them to the `SelectiveOn.Names` list.
