### ISSUE TITLE
Need an option to disable the hithack check

### ISSUE THREAD

**Issue by shikendon** [lishid/Orebfuscator#181]
Player who using auto-click script (1 click per second) are easily be kicked after continuously clicked for hours.

https://github.com/lishid/Orebfuscator/blob/90852aa5524a2919ec6fedb2af6c08a4ea1d03a6/Plugin/src/main/java/com/lishid/orebfuscator/hithack/PlayerBlockTracking.java#L62

Orebfuscator4/config.yml
```yaml
ConfigVersion: 13
Booleans:
  UseCache: true
  Enabled: false
  UpdateOnDamage: true
  NoObfuscationForMetadata: true
  NoObfuscationForOps: false
  NoObfuscationForPermission: false
  LoginNotification: true
Integers:
  MaxLoadedCacheFiles: 64
  DeleteCacheFilesAfterDays: 0
  EngineMode: 1
  InitialRadius: 1
  UpdateRadius: 2
Strings:
  CacheLocation: orebfuscator_cache
  NoObfuscationForMetadataTagName: NPC
Lists:
  TransparentBlocks: []
  NonTransparentBlocks: []
Worlds:
  Default:
    Types:
    - DEFAULT
    Enabled: true
    AntiTexturePackAndFreecam: false
    AirGeneratorMaxChance: 43
    DarknessHideBlocks: false
    BypassObfuscationForSignsWithText: false
    DarknessBlocks:
    - MOB_SPAWNER
    - CHEST
    Mode1Block: STONE
    RandomBlocks: []
    ObfuscateBlocks: []
    ProximityHider:
      Enabled: false
      Distance: 8
      SpecialBlock: STONE
      Y: 255
      UseSpecialBlock: true
      ObfuscateAboveY: false
      ProximityHiderBlocks:
      - DISPENSER
      - MOB_SPAWNER
      - CHEST
      - DIAMOND_ORE
      - WORKBENCH
      - FURNACE
      - BURNING_FURNACE
      - ENCHANTMENT_TABLE
      - EMERALD_ORE
      - ENDER_CHEST
      - ANVIL
      - TRAPPED_CHEST
      UseFastGazeCheck: true
  Normal:
    Types:
    - NORMAL
    Mode1Block: STONE
    RandomBlocks:
    - STONE
    - COBBLESTONE
    - WOOD
    - GOLD_ORE
    - IRON_ORE
    - COAL_ORE
    - LAPIS_ORE
    - TNT
    - MOSSY_COBBLESTONE
    - OBSIDIAN
    - DIAMOND_ORE
    - REDSTONE_ORE
    - CLAY
    - EMERALD_ORE
    ObfuscateBlocks:
    - GOLD_ORE
    - IRON_ORE
    - COAL_ORE
    - LAPIS_ORE
    - CHEST
    - DIAMOND_ORE
    - REDSTONE_ORE
    - GLOWING_REDSTONE_ORE
    - EMERALD_ORE
    - ENDER_CHEST
  TheEnd:
    Types:
    - THE_END
    Mode1Block: ENDER_STONE
    RandomBlocks:
    - BEDROCK
    - OBSIDIAN
    - ENDER_STONE
    - PURPUR_BLOCK
    - END_BRICKS
    ObfuscateBlocks:
    - ENDER_STONE
  Nether:
    Types:
    - NETHER
    Mode1Block: NETHERRACK
    RandomBlocks:
    - GRAVEL
    - NETHERRACK
    - SOUL_SAND
    - NETHER_BRICK
    - QUARTZ_ORE
    ObfuscateBlocks:
    - NETHERRACK
    - QUARTZ_ORE
```

It would be great have an option to disable the hithack check.
